# Handle Test Data Set

In [15]:
# Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
test_df = pd.read_csv('test.csv')

In [17]:
test_df.shape

(1459, 80)

In [18]:
test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [19]:
#Check the null values
test_df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

In [32]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1459 non-null   object
 3   LotFrontage    1459 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   LotShape       1459 non-null   object
 7   LandContour    1459 non-null   object
 8   Utilities      1459 non-null   object
 9   LotConfig      1459 non-null   object
 10  LandSlope      1459 non-null   object
 11  Neighborhood   1459 non-null   object
 12  Condition1     1459 non-null   object
 13  Condition2     1459 non-null   object
 14  BldgType       1459 non-null   object
 15  HouseStyle     1459 non-null   object
 16  OverallQual    1459 non-null   int64
 17  OverallCond    1459 non-null   int64
 18  YearBuilt      1459 non-null   int64
 19  YearRemodAdd   1459 non-null   int64
 20  RoofStyle      1459 non-null   object
 21  RoofMatl       1459 non-null   object
 22  Exterior1st    1459 non-null   object
 23  Exterior2nd    1459 non-null   object
 24  MasVnrType     1459 non-null   object
 25  MasVnrArea     1459 non-null   float64
 26  ExterQual      1459 non-null   object
 27  ExterCond      1459 non-null   object
 28  Foundation     1459 non-null   object
 29  BsmtQual       1459 non-null   object
 30  BsmtCond       1459 non-null   object
 31  BsmtExposure   1459 non-null   object
 32  BsmtFinType1   1459 non-null   object
 33  BsmtFinSF1     1459 non-null   float64
 34  BsmtFinType2   1459 non-null   object
 35  BsmtFinSF2     1459 non-null   float64
 36  BsmtUnfSF      1459 non-null   float64
 37  TotalBsmtSF    1459 non-null   float64
 38  Heating        1459 non-null   object
 39  HeatingQC      1459 non-null   object
 40  CentralAir     1459 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1459 non-null   int64
 43  2ndFlrSF       1459 non-null   int64
 44  LowQualFinSF   1459 non-null   int64
 45  GrLivArea      1459 non-null   int64
 46  BsmtFullBath   1459 non-null   float64
 47  BsmtHalfBath   1459 non-null   float64
 48  FullBath       1459 non-null   int64
 49  HalfBath       1459 non-null   int64
 50  BedroomAbvGr   1459 non-null   int64
 51  KitchenAbvGr   1459 non-null   int64
 52  KitchenQual    1459 non-null   object
 53  TotRmsAbvGrd   1459 non-null   int64
 54  Functional     1459 non-null   object
 55  Fireplaces     1459 non-null   int64
 56  GarageType     1459 non-null   object
 57  GarageYrBlt    1459 non-null   float64
 58  GarageFinish   1459 non-null   object
 59  GarageCars     1459 non-null   float64
 60  GarageArea     1459 non-null   float64
 61  GarageQual     1459 non-null   object
 62  GarageCond     1459 non-null   object
 63  PavedDrive     1459 non-null   object
 64  WoodDeckSF     1459 non-null   int64
 65  OpenPorchSF    1459 non-null   int64
 66  EnclosedPorch  1459 non-null   int64
 67  3SsnPorch      1459 non-null   int64
 68  ScreenPorch    1459 non-null   int64
 69  PoolArea       1459 non-null   int64
 70  MiscVal        1459 non-null   int64
 71  MoSold         1459 non-null   int64
 72  YrSold         1459 non-null   int64
 73  SaleType       1459 non-null   object
 74  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(38)
memory usage: 855.0+ KB

In [28]:
#Fill missing values

#test_df['LotFrontage'] = test_df['LotFrontage'].fillna(test_df['LotFrontage'].mean())
test_df['MasVnrArea'] = test_df['MasVnrArea'].fillna(test_df['MasVnrArea'].mean())
test_df['BsmtFinSF1'] = test_df['BsmtFinSF1'].fillna(test_df['BsmtFinSF1'].mean())
test_df['BsmtFinSF2'] = test_df['BsmtFinSF2'].fillna(test_df['BsmtFinSF2'].mean())
test_df['BsmtUnfSF'] = test_df['BsmtUnfSF'].fillna(test_df['BsmtUnfSF'].mean())
test_df['TotalBsmtSF'] = test_df['TotalBsmtSF'].fillna(test_df['TotalBsmtSF'].mean())
test_df['BsmtFullBath'] = test_df['BsmtFullBath'].fillna(test_df['BsmtFullBath'].mean())
test_df['BsmtHalfBath'] = test_df['BsmtHalfBath'].fillna(test_df['BsmtHalfBath'].mean())
test_df['GarageYrBlt'] = test_df['GarageYrBlt'].fillna(test_df['GarageYrBlt'].mean())
test_df['GarageCars'] = test_df['GarageCars'].fillna(test_df['GarageCars'].mean())
test_df['GarageArea'] = test_df['GarageArea'].fillna(test_df['GarageArea'].mean())

In [29]:
# MSZoning has 4 null values in the test data but in the training data there are no null values, so here the MSZoning needs to 
# be taken care of

# The data type of MSZoning is "Object" i.e. it is some category
# to check the values in MSZoning
test_df['MSZoning'].value_counts()

# There are 5 categories in MSZoning, so to fill missing values in MSZoning, we'll use mode
test_df['MSZoning'] = test_df['MSZoning'].fillna(test_df['MSZoning'].mode()[0])
test_df['Utilities'] = test_df['Utilities'].fillna(test_df['Utilities'].mode()[0])
test_df['MasVnrType'] = test_df['MasVnrType'].fillna(test_df['MasVnrType'].mode()[0])
test_df['Exterior1st'] = test_df['Exterior1st'].fillna(test_df['Exterior1st'].mode()[0])
test_df['Exterior2nd'] = test_df['Exterior2nd'].fillna(test_df['Exterior2nd'].mode()[0])
test_df['MasVnrType'] = test_df['MasVnrType'].fillna(test_df['MasVnrType'].mode()[0])
test_df['BsmtQual'] = test_df['BsmtQual'].fillna(test_df['BsmtQual'].mode()[0])
test_df['BsmtCond'] = test_df['BsmtCond'].fillna(test_df['BsmtCond'].mode()[0])
test_df['BsmtExposure'] = test_df['BsmtExposure'].fillna(test_df['BsmtExposure'].mode()[0])
test_df['BsmtFinType1'] = test_df['BsmtFinType1'].fillna(test_df['BsmtFinType1'].mode()[0])
test_df['BsmtFinType2'] = test_df['BsmtFinType2'].fillna(test_df['BsmtFinType2'].mode()[0])
test_df['Functional'] = test_df['Functional'].fillna(test_df['Functional'].mode()[0])
test_df['GarageType'] = test_df['GarageType'].fillna(test_df['GarageType'].mode()[0])
test_df['GarageCond'] = test_df['GarageCond'].fillna(test_df['GarageCond'].mode()[0])
test_df['SaleType'] = test_df['SaleType'].fillna(test_df['SaleType'].mode()[0])
test_df['KitchenQual'] = test_df['KitchenQual'].fillna(test_df['KitchenQual'].mode()[0])
test_df['GarageFinish'] = test_df['GarageFinish'].fillna(test_df['GarageFinish'].mode()[0])
test_df['GarageQual'] = test_df['GarageQual'].fillna(test_df['GarageQual'].mode()[0])

In [31]:
test_df.drop(['Alley'], axis=1, inplace=True)
test_df.drop(['PoolQC'], axis=1, inplace=True)
test_df.drop(['Fence'], axis=1, inplace=True)
test_df.drop(['MiscFeature'], axis=1, inplace=True)
test_df.drop(['FireplaceQu'], axis=1, inplace=True)

In [33]:
test_df.shape

(1459, 75)